#define a config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  name: abc
  model: def
  make: kgh

#use this configmap

containers:
- name: my-container
  image: my-image
  env:
  - name: CAR_MAKE
    valueFrom:
      configMapKeyRef:
        name: myconfig
        key: make
  - name: CAR_MODEL
    valueFrom:
      configMApKeyRef:
        name: myconfig
        key: model

#We can write the complete configuration in the configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_process 3;
    server{
      listen 80
      server_name _;
      location /{}
    }

# to se them

containers:
 - name: nginx
   image: nginx
   volumeMounts:
  - name: nginx-config
    mountPath: /etc/nginx
volumes:
- name: nginx-config
  configMap:
    name: my-nginx-config